name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
        with:
          cmake-version: '3.19.2'
          
      - name: Configure CMake
        run: cmake -S . -B build
        
      - name: Build
        run: cmake --build build
        
      - name: Run tests
        run: ctest --test-dir build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleFactory
          path: build/SimpleFactory
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: build/Testing/Temporary
