   name: CMake

   on: [push, pull_request]

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v2
         - name: Set up CMake
           uses: lukka/get-cmake@v2
           with:
             cmakeVersion: '3.19.2'
         - name: Configure CMake
           run: cmake -S . -B build
         - name: Build
           run: cmake --build build
         - name: Upload artifact
           uses: actions/upload-artifact@v2
           with:
             name: SimpleFactory
             path: build/SimpleFactory
   
